name: Update README with LeetCode Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Täglich um Mitternacht
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests beautifulsoup4

    - name: Update LeetCode Stats
      run: python update_leetcode_stats.py

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m 'Update README with latest LeetCode stats'
        git push


      
